# Geodatenanalyse 1


## Tag 2 / Block 1 - Teil 4

## Einführung in *NumPy*

Ca. 20-30 Minuten

## Inhalt
- Was ist *NumPy*?
- Überblick über *NumPy* Objekte
- Überblick über Operationen und Methoden
- Einführung in die Indizierung und das Ausschneiden
- Kurzer Überblick über die erweiterte Funktionalität
- Kurzer Einblick in die linearen Algebra
- Kurzer Überblick über die Datums- und Zeitfunktionalität

## Was ist *NumPy*?

- *NumPy* (von *Numeric Python*) ist das grundlegende Paket für wissenschaftliches Rechnen in Python
- Es ist eine Python-Bibliothek, die ein mehrdimensionales Array-Objekt, verschiedene abgeleitete Objekte (z. B. maskierte Arrays und Matrizen) und eine Reihe von Routinen für schnelle Operationen auf Arrays bereitstellt
- Darunter mathematische, logische, Formmanipulationen, Sortieren, Auswählen
- Grundlegende lineare Algebra, grundlegende statistische Operationen, Zufallssimulation und vieles mehr
- Und erweitert noch die diskrete Fourier-Transformationen

**Bemerkung**: *NumPy* wurde kürzlich mit einer Veröffentlichung im Fachjournal *Nature* geehrt: [Harris et a. (2020) Array programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2)

In [1]:
import numpy as np

Wie gehe ich mit langen Datensätzen um? 
Wie kann ich Vektoren oder Matrizen am besten verarbeiten?

Nehmen wir an wir haben *a*, *b* und *c* mit vielen Speicherplätzen, d.h. Vektoren oder *Arrays*. 

Man möchte nun folgende Berechnung mit allen Elementen durchführen: 

$c = a \cdot b$

Die Lösung in C oder C++ wäre eine Schleife:

```c
for (i = 0; i < rows; i++): {
  c[i] = a[i]*b[i];
}
```

In [2]:
a = [1, 2, 4, 2, 3]
b = [9, 8, 4, 3, 9]
c = []

for index, value in enumerate(a):
    c.append(a[index]*b[index])
    
print(c)

[9, 16, 16, 6, 27]


Genau für solche Operationen wurde *NumPy* geschrieben! 

Hiermit lassen sich Schleifen oder auch geschachtelte Schleifen vermeiden.

In [3]:
a = np.array([1, 2, 4, 2, 3])
b = np.array([9, 8, 4, 3, 9])

c = a*b

print(c)

[ 9 16 16  6 27]


Durch die Optmierung spart man bei größeren Datenmengen viel Rechenzeit:

In [4]:
a = [1, 2, 4, 2, 3]
b = [9, 8, 4, 3, 9]
c = []

In [5]:
%%timeit
for index, value in enumerate(a):
    c.append(a[index]*b[index])

1.4 µs ± 48.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
a = np.array([1, 2, 4, 2, 3])
b = np.array([9, 8, 4, 3, 9])

In [7]:
%%timeit
c = a*b

427 ns ± 18.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Überblick über *NumPy* Objekte

### Datentypen von NumPy

Ähnlich wie vorher schon besprochen hat **NumPy** unterschiedliche Datentypen.

Zusätzlich zu den bereits bekannten gibt es die Folgenden:

- **float64**: Double precision float, equivalent to two 32-bit floats

- **complex64**: Complex number, represented by two 32-bit floats (real and imaginary components)

- **complex128**: Complex number, represented by two 64-bit floats (real and imaginary components)

In [8]:
# Datentyp herausfinden
import numpy as np
a = np.array([1.54378])
print(type(a))

<class 'numpy.ndarray'>


Außerdem gibt es spezielle aber **wichtige** Datentypen:

- **Kein Wert (Engl. not a number)**: Viele Datensätze haben Lücken. Wie kann man diese beschreiben? Dafür gibt es die Konstante **np.nan**

- **Unendlich (Engl. infinity)**: Wenn eine Rechenoperation zu einem Wert führt, welcher nicht mehr darstellbar ist, dann wird dieser Wert durch die Konstante **np.inf**

In [9]:
# kein Wert
a = np.nan
print(a)

nan


In [10]:
# unendlich
a = np.inf
print(a)

inf


Zur Identifikation spezieller Werte gibt es einige Methoden:

- Diese liefern ein *boolean* Objekt mit *True* (wahr) oder *False* (falsch) zurück

- Damit kann man indizieren (kommt später)

In [11]:
# Vektor erstellen
a = np.array([np.nan, 0.234, np.inf, 3])

# Testfunktionen
nans = np.isnan(a)
print(nans)

finite = np.isfinite(a)
print(finite)

[ True False False False]
[False  True False  True]


**Hinweis**: Mit *NumPy* werden auch *imaginäre Zahlen* $\Im(z)$ berechenbar:

$z = a + bi$

$i^2 = -1$

In [12]:
# eine komplexe Zahl speichern
z = 2 + 3j
print(z)

(2+3j)


###  Objekte in *NumPy*

*NumPy* hat einige Objekte, welche man unbeding kennen sollte:

- **array**: für einen eindimensionalen Vektor
- **matrix**: für eine zweidimensionale Matrix
- **ndarray**: für ein n-dimensionales Objekt!

In [13]:
# ein Vektor
a = np.array([1, 0, 4, 6, 5, 9, 8, 9, 2])
print(a.size)
print(a.shape)
print(type(a))

9
(9,)
<class 'numpy.ndarray'>


In [14]:
# eine Matrix
A = np.matrix([[1, 2], [3, 4]])
print(A.size)
print(A.shape)
print(type(A))

4
(2, 2)
<class 'numpy.matrix'>


In [15]:
# ein mehrdimensionales Array
AA = np.array([[[ 0.,  0.,  0.,  0.], [ 0.,  0.,  0.,  0.], [ 0.,  0.,  0.,  0.]], 
               [[ 0.,  0.,  0.,  0.], [ 0.,  0.,  0.,  0.], [ 0.,  0.,  0.,  0.]]])
print(AA.size)
print(AA.shape)
print(type(AA))

24
(2, 3, 4)
<class 'numpy.ndarray'>


## Überblick über Operationen und Methoden

- **WICHTIG**: Wir müssen uns daran gewöhnen, dass eine Varibale nun ganze Zahlenreihen oder Matrizen enthalten kann

- Mit *NumPy* lassen sich viele Berechnungen vereinfacht programmieren

### Beispiele für Berechnungen

Mathematische Operationen

In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.matrix([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Matrixmultiplication
c = b.dot(a)
print(c)

[[ 55 130]]


In [17]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# quadrieren
c = b**2
print(c)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


Eingebaute Methoden (Funktionen):

In [18]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Wurzel ziehen
c = np.sqrt(b)
print(c)

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


In [19]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# kumulative Summe
c = np.cumsum(b)
print(c)

[ 1  3  6 10 15 21 28 36 45 55]


In [20]:
a = np.array([1, 2])
b = np.array([5, 3])

# lineare Interpolation
c = np.interp(1.3, a, b)
print(c)

4.4


In *NumPy* sind unzählige Funktionen eingebaut.

Einen Überblick gibt es hier: [NumPy's Mathematical Functions](https://numpy.org/doc/stable/reference/routines.math.html)

**Achtung**: Viele weiterführende mathematische Funktionen fehlen aber auch.

Dafür gibt es andere Pakete, zum Beispiel:
- [SciPy](https://www.scipy.org/): ist eine freie (BSD-lizenzierte) Python-Bibliothek für reelle und komplexe Fließkomma-Arithmetik mit beliebiger Genauigkeit

- [math](https://mpmath.org/): ist ein Python-basiertes Ökosystem von Open-Source-Software für Mathematik, Wissenschaft und Technik

Viele dieser Pakete lassen sich einwandfrei mit *NumPy* Datentypen verwenden.

Ein Beispiel für die Verwendung von **SciPy** ist die Verwendung der [Fehlerfunktion](https://de.wikipedia.org/wiki/Fehlerfunktion):

$erf(x) = \frac{2}{\sqrt{\pi}} \int_0^x{e^{-r^2}} d r$

In [21]:
import scipy.special as sp

# Fehlerfunktion ausrechnen
a = np.array([0.1, 1, 2, 3, 4])
print(sp.erf(a))

[0.11246292 0.84270079 0.99532227 0.99997791 0.99999998]


In [22]:
import mpmath as mp

# Präzision bestimmen
mp.dps = 50

# Präzision ansehen ...
print(mp.pi)
mp.nstr(mp.pi, 50)

3.14159265358979


'3.141592653589793115997963468544185161590576171875'

## Einführung in die Indizierung und das Ausschneiden

**ACHTUNG**: Verständnis dieses Teils ist sehr wichtig, da die Indizierung eines der besten Möglichkeiten für die schnelle Datenverarbeitung bietet!

Wie erfolgt der Zugriff auf einzelne Werte in einem Datenkontainer?

<p align="left">
  <img src="figures/cube.jpg" width=400 align='left' />
</p>





Durch Indizierung!

In [23]:
# ein 3D Array mit zufälligen Zahlen
a = np.random.rand(5, 5, 5)
print(a)

[[[0.3673859  0.17756745 0.16544107 0.85422259 0.44779675]
  [0.01197298 0.71649245 0.2450408  0.691531   0.1626829 ]
  [0.4897386  0.25152484 0.08911375 0.06109532 0.29627129]
  [0.45819125 0.40729052 0.65466665 0.20318133 0.87140017]
  [0.81615331 0.42939957 0.6830261  0.98934915 0.7889858 ]]

 [[0.88592486 0.16715522 0.54239313 0.7160568  0.78541266]
  [0.3166467  0.84390107 0.54211943 0.70051833 0.56278033]
  [0.45227286 0.00601564 0.264527   0.59114325 0.1265211 ]
  [0.83817172 0.22367332 0.62901986 0.51398511 0.06042844]
  [0.44323453 0.68523895 0.05890148 0.83307351 0.23899888]]

 [[0.18482661 0.60242332 0.77591234 0.42876808 0.03235423]
  [0.90752746 0.83511801 0.52440243 0.48772998 0.29091379]
  [0.43424719 0.42734538 0.56953568 0.23348437 0.31604487]
  [0.49222599 0.76281646 0.23255543 0.62418574 0.08358814]
  [0.20563113 0.81827995 0.67260066 0.55539161 0.78979739]]

 [[0.08779339 0.9723563  0.90607195 0.35806429 0.84137215]
  [0.64202427 0.27848246 0.24751236 0.76061275 0.6

Wie kann ich jetzt gezielt auf Werte zugreifen?

Zum Beispiel, gib mir alle Werte der ersten Zeile:

In [24]:
print(a[:, 0])

[[0.3673859  0.17756745 0.16544107 0.85422259 0.44779675]
 [0.88592486 0.16715522 0.54239313 0.7160568  0.78541266]
 [0.18482661 0.60242332 0.77591234 0.42876808 0.03235423]
 [0.08779339 0.9723563  0.90607195 0.35806429 0.84137215]
 [0.19146865 0.23227458 0.61270359 0.39334515 0.74462585]]


Oder, gib mir alle Werte der ersten Spalte:

In [25]:
print(a[0, :])

[[0.3673859  0.17756745 0.16544107 0.85422259 0.44779675]
 [0.01197298 0.71649245 0.2450408  0.691531   0.1626829 ]
 [0.4897386  0.25152484 0.08911375 0.06109532 0.29627129]
 [0.45819125 0.40729052 0.65466665 0.20318133 0.87140017]
 [0.81615331 0.42939957 0.6830261  0.98934915 0.7889858 ]]


Überblick:

- die Dimensionen werden beim Zugriff mit Kommas getrennt
- der Operator ":" steht für alles, was in einer Dimension vorhanden ist
- Mit diesem Operator kann man beliebige Sequenzen ansprechen

Überblick:

<p align="left">
  <img src="figures/indexing.png" width=400 align='left' />
</p>

Quelle: [Opengenus](https://iq.opengenus.org/2d-array-in-numpy/)

Machen wir ein paar Beispiele:

In [26]:
# zuerst machen wir eine Sequenz
a = np.arange(0,100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [27]:
# gib mir Zeile 3-6 der ersten Spalte
print(a[3:7, 0])

[30 40 50 60]


In [28]:
# gib mir Spalte 2-5 der ersten Zeile
print(a[0, 2:6])

[2 3 4 5]


In [29]:
# gib mir jede weite Zeile der ersten Spalte
print(a[::2, 0])

[ 0 20 40 60 80]


**Zusammenfassung**:

- Die Indizierung jeder Dimension erfolgt generell so: **Anfang:Ende:Inkrement**
- Achtung: Das Ende ist nicht mit eingerechnet, z.B. 2:5:1 wird zu [2, 3, 4]
- Das Weglassen von **Anfang**: Fängt bei null an
- Das Weglassen von **Ende**: Hört am Schluss auf
- Das Weglassen von **Inkrement**: Standard ist 1
- Negative Werte von **Inkrement**: Zugriff erfolgt rückwärts!

In [30]:
# gib mir jede weite Zeile der ersten Spalte
# aber rückwärts!
print(a[::-2, 0])

[90 70 50 30 10]


### Logische Indizierung

Werte in einem *NumPy* Objekt können auch durch logische Indizierung gefunden und bearbeitet werden.

Bei der logischen Indizierung wird zuerst ein *boolean* *Array* erstellt und verwendet. 

Dieses wird dann zur Erkennung der Werte verwendet.

In [31]:
# erstelle ein array mit Zufallswerten
a = np.random.rand(10)
idx = (a > 0.5)
print(idx)

[ True False  True  True False False  True False False False]


In [32]:
# zeige alle Wert, die über 0.2 liegen
b = a[a > 0.2]
print(b)

[0.96752362 0.84657305 0.62573478 0.2560058  0.37384204 0.51846612
 0.20182223]


In [33]:
# zeige alle Wert, die über 0.2 und unter 0.8 liegen
b = a[(a > 0.2) & (a < 0.8)]
print(b)

[0.62573478 0.2560058  0.37384204 0.51846612 0.20182223]


## Kurzer Überblick über die erweiterte Funktionalität

### Einfache Erstellung oft benötigter Objekte

Für die einfache und schnelle Erstellung von Objekten gibt es viele hilfreiche Funtionen:

In [34]:
# Erstellung eines Null-Objektes
a = np.zeros((4, 4))
print(a)

# Erstellung eines Eins-Objekts
a = np.ones((4, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Achtung**: Leider gibt es diese Funktion nicht für *NaN! Hier muss man sich etwas behelfen.

In [35]:
# Erstellung einer leeren Matrix 
a = np.empty((3, 3))
a[:] = np.nan
print(a)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


**Vorsicht**: Die Methode *empty()* setz einen Zeiger auf einen freien Speicherplatz! Die dortigen Werte können zufällig sein, sind also nicht verlässlich.

### Kombination von Objekten

Für die einfache und schnelle Kombination von Objekten gibt es hilfreiche Funtionen:

In [36]:
# erstelle zwei gleichlange Vektoren
a = np.random.rand(10)
print(a.shape)
b = np.random.rand(10)
print(b.shape)

# horizontale Kombination
c = np.hstack((a, b))
print(c.shape)
c = np.concatenate((a, b), axis=0)
print(c.shape)

# vertikale Kombination
c = np.vstack((a, b))
print(c.shape)

(10,)
(10,)
(20,)
(20,)
(2, 10)


In [37]:
# Objekt umdrehen (transpose)
print(a)
b = a.transpose
print(b)
# oder Auch
b = a.T
print(b)

[0.15141506 0.95655461 0.00508223 0.42992441 0.45601741 0.39952651
 0.10269261 0.34179717 0.71773812 0.76870422]
<built-in method transpose of numpy.ndarray object at 0x000001FC3F9924B0>
[0.15141506 0.95655461 0.00508223 0.42992441 0.45601741 0.39952651
 0.10269261 0.34179717 0.71773812 0.76870422]


### Sortieren von Werten in einem Objekt

Für die einfache und schnelle Sortierung von Werten gibt es viele hilfreiche Funtionen:

In [38]:
# erstelle zufällige Werte
a = np.random.randint(0, 10, 10)
print(a)

# sortiere diese Werte
b = np.sort(a)
print(b)

[9 7 1 4 5 2 6 3 3 1]
[1 1 2 3 3 4 5 6 7 9]


### Suchen von Werten in einem Objekt

Für die einfache und schnelle Suche von Werten gibt es viele hilfreiche Funtionen:

In [39]:
# erstelle zufällige Werte
a = np.random.randint(0, 10, 50)
print(a)

# identifiziere die Werte
bol = (a == 3)
print(bol)

# zeige den Index diser Werte
idx = np.where(bol)
print(idx)

[6 0 3 1 2 6 5 2 3 1 4 0 6 2 6 2 9 7 3 1 3 4 2 8 3 0 4 0 3 9 3 8 9 3 1 4 7
 7 8 3 9 1 7 1 5 6 7 4 6 5]
[False False  True False False False False False  True False False False
 False False False False False False  True False  True False False False
  True False False False  True False  True False False  True False False
 False False False  True False False False False False False False False
 False False]
(array([ 2,  8, 18, 20, 24, 28, 30, 33, 39], dtype=int64),)


### Einfache Statistiken

Für einfache Statistiken gibt es viele hilfreiche Funtionen:

In [40]:
# erstelle zufällige Werte
a = np.random.rand(10000)

# der kleinste Wert
b = np.min(a)
print(b)

# der Häufigste (Median) aller Werte
b = np.median(a)
print(b)

# finde den Index des maximalen Wertes
b = np.argmax(a)
print(b)

9.561138972924432e-05
0.5045254903951111
3675


### Laden von Textdateien

Auch Textdateien mit Daten können eingelesen werden:

In [41]:
# Datei zum Lesen öffnen
file = open("datasets/hydraulic_apertures.csv", "r")

# Datei in NumPy einlesen ...
data = np.genfromtxt(file, delimiter=",", skip_header=1)

# Datei schliessen
file.close()

print(data[:10, :])

[[310. 222.]
 [200. 153.]
 [160.  31.]
 [370. 584.]
 [ 90. 312.]
 [ 20. 599.]
 [ 50.  61.]
 [310.  79.]
 [ 80. 482.]
 [200. 141.]]


## Kurzer Überblick über die lineare Algebra

**Beispiel**: Lösung eines Gleichungssystems mit drei Unbekannten:

$2x + 4y -2z = 5$

$x -5y + 3z = 10$

$3x -2y -z = 8$


\begin{align*}
\left[\begin{array}{ccc}
2 & 4 & -2 \\
1 & -5 & 3 \\
3 & -2 & -1
\end{array}\right]
\begin{bmatrix}
  x  \\
  y  \\
  z
\end{bmatrix} 
= \begin{bmatrix}
  5  \\
  10  \\
  8
\end{bmatrix}
\end{align*}

\begin{align*}
\mathbf{A} \cdot x = b
\end{align*}

\begin{align*}
x = \mathbf{A}^{-1} \cdot b
\end{align*}

In [42]:
# Koeffizienten
coeff = np.matrix([[2, 4, -2], [1, -5, 3], [3, -2, -1]])

# Lösung
solution = np.matrix([[5], [10], [8]])

# Inversmatrix
coeff_inv = np.linalg.inv(coeff)

# Matrix-Multiplikation
unknown = coeff_inv.dot(solution)
print(unknown)

[[4.19444444]
 [0.72222222]
 [3.13888889]]


## Kurzer Überblick über die Datums- und Zeitfunktionalität

- Bisher haben wir nur Daten angeschaut

- Was ist mit Zeitreihen? Diese kommen häufig in den Geowissenschaften vor

- Zeitreihen sind ein langes Thema, hier gibt es nur einen kurzen EInstieg

- Mehr kommt dann später wenn das Paket *Pandas* vorgestellt wird

In [43]:
# Ein Datum
date = np.datetime64('2021-03-10')
print(date)

2021-03-10


In [44]:
# Ein Datum und eine Zeit
datetime = np.datetime64('2021-03-10T12:00')
print(datetime)

2021-03-10T12:00


Auch Zeitdifferenzen lassen sich in *NumPy* gut dastellen:

In [45]:
# eine Zeitdifferenz in Stunden
delta_t = np.timedelta64(1, 'h')
print(delta_t)

1 hours


In [46]:
# Ein Datum
date = np.datetime64('2021-03-10')
# Zeitdifferenz in Tagen
delta_t1 = np.timedelta64(3, 'D')
# Zeitdifferenz in Stunden
delta_t2 = np.timedelta64(2, 'h')
# Zeitdifferenz in Minuten
delta_t3 = np.timedelta64(22, 'm')
# das Ergebnis einer Zeitrechnung
result = date + delta_t1 + delta_t2 + delta_t3
print(result)

2021-03-13T02:22


**ACHTUNG**: Leider ist *NumPy*'s Zeitfunktionalität sehr begrenzt! Für weitere Möglichkeit benötigt man andere Pakete.

### Das *datetime* Paket in Python

- Das *datetime* Paket bietet viel mehr Funktionalität als *NumPy*

- Allerdings muss man beachten, dass es ein anderer Objekttyp ist

- Natürlich kann man Variablen konvertieren

- Leider gibt es hier oft Verwirrungen

In [47]:
import datetime as dt

In [48]:
# Beispiel eines Datumsobjektes
date = dt.datetime(2021, 3, 12)
print(date)

2021-03-12 00:00:00


In [49]:
# Beispiel eines Datums- und Zeitobjektes
datetime = dt.datetime(2021, 3, 12, 13, 15)
print(datetime)

2021-03-12 13:15:00


In [50]:
# Was ist die momentane Zeit?
now = dt.datetime.now()
print(now)

2021-03-04 17:12:11.878242


In [51]:
# Beispiel für eine Zeitdifferenz
delta_t = dt.timedelta(minutes=13, seconds=133)
print(delta_t)

0:15:13


In [52]:
# Beispiel für eine Zeitrechnung
now = dt.datetime.now()
# wieviel Zeit wollen wir dazu zählen
delta = dt.timedelta(minutes=33, seconds=13)

# wann ist das ...?
future = now + delta
print(future)

2021-03-04 17:45:24.900186


### Konvertierung zwischen *NumPy* und *datetime*

In [53]:
# von NumPy nach datetime
when = np.datetime64('2021-03-12T12:33:34').astype(datetime)
print(when)

TypeError: Cannot interpret 'datetime.datetime(2021, 3, 12, 13, 15)' as a data type

In [ ]:
# von datetime nach NumPy
when = np.datetime64(dt.datetime.now())
print(when)

In [ ]:
# an welchem Wochentag wurde ich geboren?
when = dt.datetime(1981, 4, 4)
print(when.weekday())
print(when.strftime('%A'))

## Weitere Funktionalität

Was hier präsentiert wurde waren nur die absoluten Grundlagen von *NumPy* und *datetime*.

- Einen Überblick über *NumPy* gibt es hier: [*NumPy* Referenz](https://numpy.org/doc/stable/reference/)

- Einen Überblick über *datetime* gibt es hier: [*datetime* Referenz](https://docs.python.org/3/library/datetime.html)

## ENDE